export const paths = {
  landing: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  decks: "/decks",
  deck: "/decks/:deckId",
  cards: "/decks/:deckId/cards",
  cardImport: "/decks/:deckId/cards/import",
  study: "/study",
  studySession: "/study-sessions/:sessionId",
  statistics: "/statistics",
  profile: "/profile",
  forum: "/forum",
  forumCategory: "/forum/categories/:categorySlug",
  forumNewTopic: "/forum/categories/:categorySlug/new",
  forumTopic: "/forum/topics/:topicId",
} as const;
