spring.application.name=loopy

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/loopy
spring.datasource.username=rashid
spring.datasource.password=rashid

app.jwt.secret=Pgd8YOXIsKaZiB8H35t2p5TDLJmFtbmeHnLzrcST6Bi0ySGdgNshZkQpAKlZqEGt9YzbrLaC2FpkqOJW5v/PBg==
app.jwt.ExpirationMs=9000000

security.allowedOrigins=http://localhost:3000
